name: IGI Releases & Updates Annoncements

description: "IGI Releases & Updates Announcements pages"

url: "http://caifti.github.io/igi_release"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true
